version: '3.7'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  producer:
    container_name: producer
    image: black82/ecabs:v.001
    ports:
      - 8080:8080
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - backend
  consumer:
    container_name: consumer
    image: black82/saveservice:v.001
    ports:
      - 8081:8081
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - backend

networks:
  backend: