version: '3.7'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - backend

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dokerfile
    ports:
      - 8080:8080
    restart: always
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    networks:
      - backend


volumes:
  db:
networks:
  backend: